# Configuración para la base de datos en memoria H2
spring:
  datasource:
    url: jdbc:h2:mem:bdatos
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    #defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false

  # Configuración para almacenamiento basado en archivos
  # spring:
  #   datasource:
  #     url: jdbc:h2:file:/data/demo

